---
title: Landing  Page Creacion
timezone: Europe/Paris
collections:
  header:
    title: Header - la oferta
    output: true
  planes:
    title: Planes
    output: true
  posts:
    title: Posts
    output: true
  params:
    title: SEO
    output: true
  sobre-nosotros:
    title: Sobre nosotros
    output: true
  uploads:
    title: Uploads
    output: true
plugins:
- jekyll-sitemap
