---
title: Landing Creacion
timezone: Europe/Paris
collections:
  people:
    title: People
    output: false
  posts:
    title: Posts
    output: true
  sections:
    title: Sections
    output: false
  uploads:
    title: Uploads
    output: true
plugins:
- jekyll-sitemap
description: 
