---
title: Landing  Page Creacion
timezone: Europe/Paris
collections:
  header:
    title: Header
    output: true
  nosotros:
    title: Nosotros
    output: true
  params:
    title: Params
    output: true
  planes:
    title: Planes
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
plugins:
- jekyll-sitemap
